import "dotenv/config";
import fs from "node:fs";

// Detect Speechify's audio watermark. Self-contained: we first SYNTHESIZE a clip
// (Speechify's own output carries the watermark), then run both watermark checks:
//   - /detect (needs your API key)  → { watermarked, confidence }
//   - /verify (no credential at all) → { watermarked }  (public, CA AI Transparency Act)
//
// Read the answer in ONE direction only: watermarked:true is positive evidence the
// audio is Speechify-generated. watermarked:false is ABSENCE of evidence, not proof
// of the negative — only models redeployed since the watermark shipped mark output,
// the detector needs ≥3s of clear speech, and re-encoding/speed changes degrade the mark.

const token = process.env.SPEECHIFY_API_KEY;
if (!token) {
  throw new Error("Set SPEECHIFY_API_KEY (copy .env.example to .env).");
}

const BASE = "https://api.speechify.ai";

interface SpeechResponse {
  audio_data: string; // base64-encoded audio
}
interface DetectResponse {
  watermarked: boolean;
  confidence: number; // 0..1
}
interface VerifyResponse {
  watermarked: boolean; // no confidence on the credential-free endpoint
}

async function main() {
  // 1. Synthesize ~4s of speech to WAV so we have watermarked audio to test.
  //    The detector needs ≥3s of clear speech, so keep the sentence long enough.
  const speechRes = await fetch(`${BASE}/v1/audio/speech`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      input:
        "This clip was generated by Speechify so it carries an inaudible audio watermark. " +
        "We will now detect that watermark two different ways.",
      voice_id: "geffen_32",
      audio_format: "wav",
      model: "simba-3.2",
    }),
  });
  if (!speechRes.ok) {
    throw new Error(`POST /v1/audio/speech → ${speechRes.status}: ${await speechRes.text()}`);
  }
  const speech = (await speechRes.json()) as SpeechResponse;
  fs.writeFileSync("sample.wav", Buffer.from(speech.audio_data, "base64"));
  console.log("Wrote sample.wav");

  // Multipart body reused by both checks. Let fetch set the multipart boundary —
  // do NOT set Content-Type yourself. Field name is `audio`, file must be ≤25MB.
  const buildForm = () => {
    const form = new FormData();
    form.append(
      "audio",
      new Blob([fs.readFileSync("sample.wav")], { type: "audio/wav" }),
      "sample.wav",
    );
    return form;
  };

  // 2. DETECT (with key): richer answer including a confidence score. Capped ~20/hour
  //    per workspace. 422 watermark_audio_unusable = undecodable/too little audio (NOT
  //    a negative verdict); 502 watermark_detection_unavailable = transient, retry.
  const detectRes = await fetch(`${BASE}/v1/audio/watermark/detect`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}` },
    body: buildForm(),
  });
  if (!detectRes.ok) {
    throw new Error(
      `POST /v1/audio/watermark/detect → ${detectRes.status}: ${await detectRes.text()}`,
    );
  }
  const detect = (await detectRes.json()) as DetectResponse;
  console.log(
    `detect  → watermarked=${detect.watermarked} confidence=${detect.confidence.toFixed(3)}`,
  );

  // 3. VERIFY (no credential): the public, credential-free check mandated by the CA
  //    AI Transparency Act. Send NO Authorization header. Rate-limited per client IP.
  //    Returns a bare boolean — no confidence score.
  const verifyRes = await fetch(`${BASE}/v1/audio/watermark/verify`, {
    method: "POST",
    body: buildForm(),
  });
  if (!verifyRes.ok) {
    throw new Error(
      `POST /v1/audio/watermark/verify → ${verifyRes.status}: ${await verifyRes.text()}`,
    );
  }
  const verify = (await verifyRes.json()) as VerifyResponse;
  console.log(`verify  → watermarked=${verify.watermarked}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
