#!/usr/bin/env bash
set -euo pipefail

# Speechify — detect the audio watermark (Bash + curl + jq).
# Self-contained: SYNTHESIZE a clip (Speechify's output carries the watermark), then
# run both checks:
#   - /detect (needs your API key)  -> { watermarked, confidence }
#   - /verify (no credential at all) -> { watermarked }  (public, CA AI Transparency Act)
#
# Read the answer in ONE direction only: watermarked=true is positive evidence the audio
# is Speechify-generated. watermarked=false is ABSENCE of evidence, not proof of the
# negative — only models redeployed since the watermark shipped mark output, the detector
# needs >=3s of clear speech, and re-encoding/speed changes degrade the mark.

cd "$(dirname "$0")"

if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
fi

: "${SPEECHIFY_API_KEY:?Set SPEECHIFY_API_KEY (copy .env.example to .env).}"

BASE="https://api.speechify.ai"

# 1. Synthesize ~4s of speech to WAV so we have watermarked audio to test.
#    The detector needs >=3s of clear speech, so keep the sentence long enough.
speech_response=$(curl --fail-with-body --silent --show-error \
  -X POST "${BASE}/v1/audio/speech" \
  -H "Authorization: Bearer ${SPEECHIFY_API_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "input": "This clip was generated by Speechify so it carries an inaudible audio watermark. We will now detect that watermark two different ways.",
    "voice_id": "geffen_32",
    "audio_format": "wav",
    "model": "simba-3.2"
  }')

# macOS base64 lacks `--decode`; the short `-d` flag works on both BSD and GNU coreutils.
printf '%s' "$speech_response" | jq -r '.audio_data' | base64 -d > sample.wav
echo "Wrote sample.wav"

# 2. DETECT (with key): richer answer including a confidence score. Capped ~20/hour per
#    workspace. `curl -F "audio=@..."` builds the multipart body and sets the boundary.
#    The field name is `audio` and the file must be <=25MB. 422 watermark_audio_unusable
#    = undecodable/too little audio (NOT a negative verdict); 502
#    watermark_detection_unavailable = transient, retry.
detect=$(curl --fail-with-body --silent --show-error \
  -X POST "${BASE}/v1/audio/watermark/detect" \
  -H "Authorization: Bearer ${SPEECHIFY_API_KEY}" \
  -F "audio=@sample.wav;type=audio/wav")
printf 'detect  -> %s\n' "$(printf '%s' "$detect" | jq -r '"watermarked=\(.watermarked) confidence=\(.confidence)"')"

# 3. VERIFY (no credential): the public, credential-free check mandated by the CA AI
#    Transparency Act. Send NO Authorization header. Rate-limited per client IP. Returns
#    a bare boolean — no confidence score.
verify=$(curl --fail-with-body --silent --show-error \
  -X POST "${BASE}/v1/audio/watermark/verify" \
  -F "audio=@sample.wav;type=audio/wav")
printf 'verify  -> %s\n' "$(printf '%s' "$verify" | jq -r '"watermarked=\(.watermarked)"')"
