import base64
import os

import requests
from dotenv import load_dotenv

# Detect Speechify's audio watermark. Self-contained: we first SYNTHESIZE a clip
# (Speechify's own output carries the watermark), then run both watermark checks:
#   - /detect (needs your API key)  -> { watermarked, confidence }
#   - /verify (no credential at all) -> { watermarked }  (public, CA AI Transparency Act)
#
# Read the answer in ONE direction only: watermarked=True is positive evidence the
# audio is Speechify-generated. watermarked=False is ABSENCE of evidence, not proof of
# the negative — only models redeployed since the watermark shipped mark output, the
# detector needs >=3s of clear speech, and re-encoding/speed changes degrade the mark.

BASE = "https://api.speechify.ai"


def main() -> None:
    load_dotenv()

    token = os.environ.get("SPEECHIFY_API_KEY")
    if not token:
        raise SystemExit("Set SPEECHIFY_API_KEY (copy .env.example to .env).")

    # 1. Synthesize ~4s of speech to WAV so we have watermarked audio to test.
    #    The detector needs >=3s of clear speech, so keep the sentence long enough.
    speech_resp = requests.post(
        f"{BASE}/v1/audio/speech",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={
            "input": (
                "This clip was generated by Speechify so it carries an inaudible audio "
                "watermark. We will now detect that watermark two different ways."
            ),
            "voice_id": "geffen_32",
            "audio_format": "wav",
            "model": "simba-3.2",
        },
        timeout=60,
    )
    speech_resp.raise_for_status()
    with open("sample.wav", "wb") as f:
        f.write(base64.b64decode(speech_resp.json()["audio_data"]))
    print("Wrote sample.wav")

    # 2. DETECT (with key): richer answer including a confidence score. Capped ~20/hour
    #    per workspace. `requests` sets the multipart boundary from files={...}; the
    #    field name is `audio` and the file must be <=25MB. 422 watermark_audio_unusable
    #    = undecodable/too little audio (NOT a negative verdict); 502
    #    watermark_detection_unavailable = transient, retry.
    with open("sample.wav", "rb") as audio:
        detect_resp = requests.post(
            f"{BASE}/v1/audio/watermark/detect",
            headers={"Authorization": f"Bearer {token}"},
            files={"audio": ("sample.wav", audio, "audio/wav")},
            timeout=60,
        )
    detect_resp.raise_for_status()
    detect = detect_resp.json()
    print(f"detect  -> watermarked={detect['watermarked']} confidence={detect['confidence']:.3f}")

    # 3. VERIFY (no credential): the public, credential-free check mandated by the CA
    #    AI Transparency Act. Send NO Authorization header. Rate-limited per client IP.
    #    Returns a bare boolean — no confidence score.
    with open("sample.wav", "rb") as audio:
        verify_resp = requests.post(
            f"{BASE}/v1/audio/watermark/verify",
            files={"audio": ("sample.wav", audio, "audio/wav")},
            timeout=60,
        )
    verify_resp.raise_for_status()
    verify = verify_resp.json()
    print(f"verify  -> watermarked={verify['watermarked']}")


if __name__ == "__main__":
    main()
